server:
  port: 8088 # tomcat端口号
spring:
  redis:
    database: ${AUTH_REDIS_DATABASE:0}
    host: ${AUTH_REDIS_HOST:127.0.0.1}
    port: ${AUTH_REDIS_PORT:6379}
    password: ${AUTH_REDIS_PASSWORD:}
    max-wait: 30000 # 连接池最大阻塞等待时间
    max-active: 100 # 连接池最大连接数
    max-idle: 20 # 连接池最大的空闲连接
    min-idle: 0 # 连接池最小的空闲连接
    timeout: 3000 #连接超时
#  datasource:
#    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1:3306}/${MYSQL_DB_NAME:rj_cad}?rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
#    username: ${MYSQL_USERNAME:root}
#    password: ${MYSQL_PASSWORD:root}
  datasource:
    dynamic:
      primary: mysql
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        mysql:
          url: jdbc:mysql://127.0.0.1:3306/drawings?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
          maxActive: 30
          initialSize: 5
          minIdle: 2
#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: 4
      # 默认数据库表下划线命名
      table-underline: true
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true
  codec:
    max-in-memory-size: 2048
  mail:
    default-encoding: utf-8